### ISSUE TITLE
feat: add tests for firebase security rules

### ISSUE THREAD

**Issue by d3lm** [machinelabs/machinelabs#688]
Here's a great library that lets you test your firebase security rules without connecting to the real database. All it needs are the security rules and some mock data.

https://github.com/goldibex/targaryen

Once we migrate to Firestore, we may need to look into this little gem here:
https://github.com/GitbookIO/expect-firestore

As of right now, targaryen does not support Firestore.

**Comment by PascalPrecht** [comment]
This has landed in several commits.
