### ISSUE TITLE
fix: lock down max length of certain fields

### ISSUE THREAD

**Issue by cburgdorf** [machinelabs/machinelabs#725]
We should lock down the length of strings that certain fields allow. We can create shorthand types for that

```
type String30 extends String {
  validate() { this.length <= 30 }
}

type String10 extends String {
validate() { this.length <= 10 }
}
```

and then use where appropriate

**Comment by SamVerschueren** [comment]
What fields are we talking about here? Just for a little more context :).

**Comment by cburgdorf** [comment]
Pretty much all of the db fields should have some kind of sane max length. Except for the actual lab directory data maybe. Right now, people can put a string with 2.5 million character in e.g the lab title.

https://stackoverflow.com/questions/35531500/whats-the-longest-string-i-can-save-and-get-using-firebase

**Comment by SamVerschueren** [comment]
Isn't this something that should be checked at runtime? As all these values are basically dynamic coming from the client, it wouldn't make much sense to restrict them. But might be missing something regarding the types :).

**Comment by cburgdorf** [comment]
Sure the client and also the CLI should check the values as well. But since everyone can write into the firebase (even with own scripts) we need to have sensible limits on the firebase level as well.

For instance, this is the bolt model of our lab

```
type Lab {
  id: String,
  user_id: String,
  name: String,
  description: String,
  has_cached_run: Boolean | Null,
  cache_hash: String | Null
  tags: String[],
  directory: String,
  hidden: Boolean,
  created_at: Number,
  modified_at: Number,
  fork_of: String | Null,
  is_private: Boolean
}
```

Since the ID is specified as `String` without further validation I can easily save a lab in our database that has an id with 1 million characters. 

I think we can just create some basic types such as

```
type String100 extends String {
  validate() { this.length <= 100 }
}

type String1000 extends String {
  validate() { this.length <= 100 }
}
```

And then use them like this.

```
type Lab {
  id: String100,
  user_id: String100,
  name: String100,
  description: String1000,
  has_cached_run: Boolean | Null,
  cache_hash: String100 | Null
  tags: String100[], <-- not sure if that would be supported
  directory: String, <-- this one would probably stay unbound
  hidden: Boolean,
  created_at: Number,
  modified_at: Number,
  fork_of: String100 | Null,
  is_private: Boolean
}
```

Does that make sense to you?

**Comment by SamVerschueren** [comment]
Is this a firebase type? Is it possible to declare custom types for firebase? I believe I'm confused :), it looks like you try to enforce the limit with TypeScript.

**Comment by cburgdorf** [comment]
It's a custom bolt type. It will be compiled down to the correct firebase security rules by the bolt compiler.

We already use similar constructs to declare that some fields may only be writable by the server etc. 


https://github.com/machinelabs/machinelabs/blob/master/firebase/database.rules.bolt#L105

**Comment by cburgdorf** [comment]
Let me elaborate a bit on that because I wrote the last answer from mobile. Our firebase security rules (which are responsible to restrict read/write access, datatypes, length of fields etc) live in [database.rules.json](https://github.com/machinelabs/machinelabs/blob/ea52e0d5367fa577c35c37bea19529ac7017ba74/firebase/database.rules.json) but we aren't touching that file manually. Defining these rules in plain JSON is a pain in the ass but luckily firebase developed a language called bolt that gives us a higher level syntax. We define our rules in [database.rules.bolt](https://github.com/machinelabs/machinelabs/blob/ea52e0d5367fa577c35c37bea19529ac7017ba74/firebase/database.rules.bolt) and invoke `firebase-bolt database.rules.bolt` to generate the `database.rules.json` file.

Notice that as of right now, the only way for us to test these rules is to manually perform actions against the database or use the online firebase rules sandbox. However, there's a [PR](https://github.com/machinelabs/machinelabs/pull/699) from @d3lm (that unfortunately became stale even though it just needs a couple of minor tweaks) which lets us write tests against firebase security rules which is super cool.
