### ISSUE TITLE
Going Open Source

### ISSUE THREAD

**Issue by cburgdorf** [machinelabs/machinelabs#752]
As we have all agreed to open source MachineLabs this ticket serves as a starting point to collect items that need to be done to get things going.

- [x] remove sensible information from github issues
- [x] add license files + change license in `package.json` - **covered in https://github.com/machinelabs/machinelabs/pull/756**
- [ ] reword Patreon campaign
- [x] reword website + docs - **covered in https://github.com/machinelabs/machinelabs/pull/762 and https://github.com/machinelabs/docs.machinelabs.ai/pull/11**
- [x] write blog post - **covered in https://github.com/machinelabs/blog/pull/17/**
- [x] make sure developer onboarding is smooth (how to get up and running) - **covered in https://github.com/machinelabs/machinelabs/pull/756**
- [x] flag issues as `Good first starter`
- [x] add `CONTRIBUTING.md` to streamline contributions - **covered in https://github.com/machinelabs/machinelabs/pull/756**
- [x] add prettier to ensure consistency in code formatting. Make sure this is checked during CI - **covered in https://github.com/machinelabs/machinelabs/pull/763**
- [x] create gitter/slack room
- [x] streamline github labels (e.g. `comp: ....` labels are ambiguous)
- [x] add official code of conduct - **covered in https://github.com/machinelabs/machinelabs/pull/756**
- [x] set up conduct@machinelabs.ai email address
- [x] Populate generated changelog in CHANGELOG.md - **will be covered in https://github.com/machinelabs/machinelabs/pull/760**

**Comment by PascalPrecht** [comment]
🎉
