### ISSUE TITLE
Editor view main content scrools horizontally

### ISSUE THREAD

**Issue by PascalPrecht** [machinelabs/machinelabs#776]
#### Bug, feature request, or proposal:

This is a bug.

#### What is the expected behavior?

The main content of the editor view (basically everything between toolbar and footer) shouldn't scroll horizontally as MachineLabs should take the whole available space for that.

#### What is the current behavior?

It seems that there's some CSS issues, the main content scrolls horizontally as soon as any of the sidenavs are opened. See this gif:

![mar-29-2018 15-24-01](https://user-images.githubusercontent.com/445106/38091257-49bc4b86-3365-11e8-96e7-36e6acf818e2.gif)

#### What are the steps to reproduce?

Open https://machinelabs.ai in firefox and open the filetree drawer.

#### Which version of MachineLabs (or the package) is affected ?

0.28.1

**Comment by PascalPrecht** [comment]
Okay, so it turns out that we need to inform monaco editor to layout again after we opened/closed the file drawer. If we don't do it, then monaco keeps the absolute calculated width from the first paint.

In theory this is easily fixed. With the current API available we just have to inject `MonacoEditorService` and call `monacoEditorService.editor.layout(dimensions)` when the file drawer emits `openedChange()`.

This could be even nicer if monaco editor came with an API `layout(dimensions?)`, so a consumer of the editor doesn't have to inject the service and can just call it straight on the component instance a la

```
<drawer (openedChange)="monacoEditor.layout()">
 ...
</drawer>
<monaco-editor #monacoEditor>...</monaco-editor>
```

Poking @SamVerschueren here.

However, in practice this introduces a lot of jank as the browser has to repaint the whole editor after the file tree has been toggled. Not sure yet if we can do anything about it. 

If anyone has an idea, I'd be happy to hear!

**Comment by SamVerschueren** [comment]
If I'm not mistaken, Monaco is able to resize itself by setting a property on bootstrap. Let me have a look and I'll get back to you.

**Comment by PascalPrecht** [comment]
@SamVerschueren did you have time to look into monaco? I think we should get this fixed rather soonish.
