### ISSUE TITLE
Deployment of firebase rules fails with an unexpected error

### ISSUE THREAD

**Issue by pas2al** [machinelabs/machinelabs#777]
#### Bug, feature request, or proposal:
When trying to run `npx yarn run deploy` in `/firebase/functions` the command fails with an unexpected error.

#### What is the expected behavior?
The deployment should work :-)

#### What is the current behavior?
```i  deploying database, storage, functions
i  database: checking rules syntax...
✔  database: rules syntax for database machinelabs-b191b is valid
i  storage: checking rules/storage.rules for compilation errors...
✔  storage: rules file rules/storage.rules compiled successfully
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  storage: uploading rules rules/storage.rules...
i  functions: preparing functions/dist directory for uploading...
i  functions: packaged functions/dist (45.9 KB) for uploading

Error: An unexpected error has occurred.
error An unexpected error occurred: "Command failed.
Exit code: 2
Command: sh
Arguments: -c npm run build && firebase deploy && npm run clean_dist
Directory: /Users/pascal/Repositories/machinelabs/firebase/functions
Output:
".
```

yarn-log:
```Trace: 
  Error: Command failed.
  Exit code: 2
  Command: sh
  Arguments: -c npm run build && firebase deploy && npm run clean_dist
  Directory: /Users/pascal/Repositories/machinelabs/firebase/functions
  Output:
  
      at ProcessTermError.MessageError (/Users/pascal/Repositories/machinelabs/firebase/functions/node_modules/yarn/lib/cli.js:186:110)
      at new ProcessTermError (/Users/pascal/Repositories/machinelabs/firebase/functions/node_modules/yarn/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/Users/pascal/Repositories/machinelabs/firebase/functions/node_modules/yarn/lib/cli.js:30281:17)
      at ChildProcess.emit (events.js:127:13)
      at maybeClose (internal/child_process.js:933:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```

#### What are the steps to reproduce?
Follow every step in the developer guide up the the section for `#### Deploying Firebase rules and functions
`

#### Which version of MachineLabs (or the package) is affected ?
latest on master

#### Please execute the following commands in your terminal and post the output here

```
xterm-256color iTerm.app 3.1.5 /usr/local/bin/fish
```
```
v9.6.1
```
firebase --version:
```
3.17.7
```

**Comment by PascalPrecht** [comment]
@pas2al thank you for reporting this issue.

I tried to reproduce it without luck. However, I ran into a different problem but that is rather related to whether you have `yarn` globally installed or not.

See: https://github.com/machinelabs/machinelabs/pull/778#issue-178519852

I think chances are rather low according to your error log, that this is your problem as well, but maybe you can give it a try.

Another thing you can do is running

```
$ npx firebase deploy
```

separately and see if it shows more.

**Comment by pas2al** [comment]
Hey @PascalPrecht, it works using `$ npx firebase deploy`. Should i update the developer guide accordingly?

**Comment by PascalPrecht** [comment]
@pas2al this has been fixed with https://github.com/machinelabs/machinelabs/pull/778#issue-178519852 and therefore shouldn't be a problem anymore in the first place.

The dev guide also only mentions to run `npm run deploy` which abstracts away the actual `npx firebase deploy` command. So that should do it: https://github.com/machinelabs/machinelabs/blob/master/DEVELOPERS_GUIDE.md#deploying-firebase-rules-and-functions

You can try it out on latest master. Everything should work as expected, without you needing to explicitly `npx firebase deploy`.

Can you verify please?

**Comment by pas2al** [comment]
Verified. It works! Going to close the issue.

**Comment by PascalPrecht** [comment]
Yay, happy it works for you now! Keep us posted no how it goes. 

As always: some good issues to start with are here: https://github.com/machinelabs/machinelabs/issues?q=is%3Aissue+is%3Aopen+label%3A%22hotlist%3A+community-help%22
