### ISSUE TITLE
bug: firebase rule to check on value length of array values does not work

### ISSUE THREAD

**Issue by maartentibau** [machinelabs/machinelabs#800]
#### Bug:
The test for checking if the values of an array are not longer than 50 characters fail for `Labs` firebase rules.

#### What is the expected behavior?
The test should pass

#### What is the current behavior?
The test fails, because the `testLab` object in now using the correct format, before the `cannotWrite` statement was always `true` because the `testLab` format was wrong from the start.

#### What are the steps to reproduce?
Change the `testLab` to the correct format, `created_at` and `modified_at` were missing.

```
const testLab = {
  id: '1',
  user_id: currentUser.uid,
  name: 'some-name',
  description: 'some-description',
  tags: ['t', 'a', 'g', 's'],
  directory: 'some-directory',
  created_at: Date.now(),
  modified_at: Date.now(),
  hidden: false,
  is_private: false
};
```

#### Which version of MachineLabs (or the package) is affected ?
All

#### Is there anything else we should know?
If you look at the Bolt manual it should actually work [https://github.com/firebase/bolt/blob/master/docs/language.md#types](https://github.com/firebase/bolt/blob/master/docs/language.md#types)

But if you look at the JSON code that is generated, it doesn't really make much sense.

```
"tags": {
  "$key1": {
    ".validate": "newData.isString() && newData.val().length <= 50"
  },
  ".validate": "newData.hasChildren()"
},
```

#### Please execute the following commands in your terminal and post the output here

```
xterm-256color iTerm.app 3.1.6 zsh 5.3 (x86_64-apple-darwin17.0)
```

```
9.2.0
```

```
0.27.1+utc.2018.Feb.11-10.05.32
```

**Comment by cburgdorf** [comment]
The generated rule looks good to me. `String50[]` just means that each tag in that array is not allowed to exceed 50 chars.

This is what is achieved with 

```
"tags": {
  "$key1": {
    ".validate": "newData.isString() && newData.val().length <= 50"
  },
  ".validate": "newData.hasChildren()"
},
```

Notice that `$key1` is just a placeholder for the the generated key. However, what currently isn't covered is that there may be a maximum of n tags.

**Comment by maartentibau** [comment]
@cburgdorf if you run the test, you'll see that `String50[]` actually doens't work in the current `Labs` unit tests.  Just add the `created_at` and `modified_at` params to the `testLab`.

@PascalPrecht verified that the test fails.
