### ISSUE TITLE
Add indicator on lab card that execution has outputs attached to it

### ISSUE THREAD

**Issue by PascalPrecht** [machinelabs/machinelabs#811]
#### Bug, feature request, or proposal:

This is a feature.

#### What is the expected behavior?

It would be really nice if we could see, just by looking at a lab card, whether an execution has generated outputs or not. Maybe we can show a little icon or something in the execution item. Or, if it's feasible from a UI/UX point of view, add a little carousel with the first three items or so attached to that execution. It would be really neat if one could click on such an item and would end up in the preview view of that output right away.

However, I'd be fine with just adding an icon for now so we can see immediately which execution has an at least one output.

#### What is the current behavior?

Right now, the lab card only shows the lab information, plus the first couple executions attached to that lab:

<img width="386" alt="screen shot 2018-05-08 at 12 32 52" src="https://user-images.githubusercontent.com/445106/39752514-fa765898-52bb-11e8-9261-61edf65af74f.png">

#### What is the use-case or motivation for changing an existing behavior?

This change would make it easier to quickly see which executions are "interesting".

**Comment by Jefiozie** [comment]
Hi @PascalPrecht,

I had a look at this issue and I will give it a try. 

Below I've added a screenshot where I only do a check if there are one or more `output-files`. If there are `output-files` it will show the icon. For now I use `OutputFilesService` in the `ExecutionCardComponent` to check if the execution has outputs. You can see my branch [here](https://github.com/Jefiozie/machinelabs/commit/4accff975f4c22939727d4a2748d951d93c303c2)

![image](https://user-images.githubusercontent.com/17835373/43856850-f2666b44-9b49-11e8-80ef-96b3f66f1460.png)

It think this is not the correct implementation and we should get it from a higher component that passes the reference down to the `ExecutionCardComponent`. Do you agree on this?

**Comment by PascalPrecht** [comment]
@Jefiozie that's awesome! It's a little bit hard to judge for me to be honest, without seeing the code. Would you mind sending a PR so we can iterate over it? :)

I promise this lands faster than the other one! haha

**Comment by PascalPrecht** [comment]
Thanks! Taking a look!
