### ISSUE TITLE
Replace current progress bar with material progress bar

### ISSUE THREAD

**Issue by PascalPrecht** [machinelabs/machinelabs#813]
#### Bug, feature request, or proposal:

This is a refactoring

#### What is the expected behavior?

Angular Material comes with a great progress bar that is highly configurable and comes with several different modes. I think we should use it instead of the currently used ng2-slim-loading-bar as it doesn't seem to be longer maintained, plus, we'd get rid off another third party dependency.

That being said, we probably have to introduce our own progressbar service to remote control it from different places in our app. Angular Material doesn't provide such a service as of today.

#### What is the current behavior?

Right now we're using [ng2-slim-loading-bar](https://github.com/akserg/ng2-slim-loading-bar) which is no longer maintained.

#### What is the use-case or motivation for changing an existing behavior?

Reducing amount of third party dependencies, plus, Angular Material's progress bar comes with additional modes (buffer for example) that we can make use of.

**Comment by PascalPrecht** [comment]
This just became a higher priority as we can't fully upgrade to RxJS v6 without compat, as ng2-slim-loading-bar doesn't support it.

**Comment by Jefiozie** [comment]
I'm having some problems with the Developer Guide to setup my machine. But for now I made a quick stackblitz so we can discuss the issue. 

I started with a really simple way of showing and hiding the progress bar.Maybe you can have a look and tell me what you more expect. In the mean time I will try and get my machine running with the setup provided in the developer guide.

**Comment by PascalPrecht** [comment]
Hey @Jefiozie !

Wow, awesome you've already built something. Can you tell us where you're stuck with the dev guide? Chances are we need to improve it then. Also, we obviously want you to send a pull request as well :)

For quick feedback, join our chat at https://gitter.im/machinelabs/machinelabs
