### ISSUE TITLE
Bug: When running npm run format:fix it fails

### ISSUE THREAD

**Issue by Jefiozie** [machinelabs/machinelabs#827]
When I run `npm run format:fix` I get the following error. 
```
$ npm run format:fix

> @machinelabs/client@0.30.2 format:fix machinelabs\client
> npm run format:base -- --write


> @machinelabs/client@0.30.2 format:base machinelabs\client
> npm run prettier -- '{src,e2e}/**/*{.ts,.js,.json,.css,.scss}' "--write"


> @machinelabs/client@0.30.2 prettier machinelabs\client
> prettier --config ../.prettierrc --ignore-path ../.prettierignore "'{src,e2e}/**/*{.ts,.js,.json,.css,.scss}'" "--write"

[error] No matching files. Patterns tried: '{src,e2e}/**/*{.ts,.js,.json,.css,.scss}' !**/node_modules/** !./node_modules/**
npm ERR! code ELIFECYCLE
```

This is already discussed via gitter with @PascalPrecht. His initial thoughts: 

> I fear this has to do with the globbing patterns. They are prolly not supported on windows as they use \ instead of /

#### Please execute the following commands in your terminal and post the output here
OS: Windows
Node: v9.11.1
Yarn: 1.6.0

**Comment by PascalPrecht** [comment]
@d3lm can you look into this please?

**Comment by d3lm** [comment]
Will take a look. My bet is the glob too, as @PascalPrecht already mentioned. I'll have a look on how to make this work on both operating systems.

**Comment by Jefiozie** [comment]
Thanks if you want me to reproduce things let me know.

**Comment by PascalPrecht** [comment]
@d3lm what's the status of this?

**Comment by SamVerschueren** [comment]
Instead of the single quotes around the globs, can you try double quotes?

`'{src,e2e}/**/*{.ts,.js,.json,.css,.scss}'`
->
`"{src,e2e}/**/*{.ts,.js,.json,.css,.scss}"`

Escape the double quotes in the npm script. I don't have a Windows machine so can't test if this works.

**Comment by Jefiozie** [comment]
Hi @SamVerschueren just checked this one my machine and changing it resolves the issue.
I changed it to: `"format:base": "npm run prettier -- \"{src,e2e}/**/*{.ts,.js,.json,.css,.scss}\""`
If this also works on a other OS (not windows) I can make the PR for it?

**Comment by SamVerschueren** [comment]
I believe it does as it's in the docs of Prettier, feel free to make the PR and I'll verify it afterwards.

**Comment by PascalPrecht** [comment]
You rock! Thanks for pushing this forward.
