### ISSUE TITLE
Running server build step results in a error

### ISSUE THREAD

**Issue by Jefiozie** [machinelabs/machinelabs#831]
### Bug Report

|    Q               |   A
|--------------------| ------
| Breaking change    | no
| Version            | 

#### Summary
When running the command: `npx yarn build --env=dev && node dist/index.js` (dev is my personal env)
I get the following result:
```
npx: installed 1 in 1.787s
The "path" argument must be of type string
machinelabs2\server\node_modules\yarn\bin\yarn.js
yarn run v1.5.1
$ node ./build/build.js --env=dev
cp ./src/environments/personal/environment.dev.ts ./src/environments/environment.ts
Building shared libs before building the server
Building shared libs...
npx: installed 1 in 2.066s
The "path" argument must be of type string
machinelabs2\shared\models\node_modules\typescript\bin\tsc
npx: installed 1 in 1.988s
The "path" argument must be of type string
machinelabs2\shared\core\node_modules\typescript\bin\tsc
npx: installed 1 in 1.815s
The "path" argument must be of type string
machinelabs2\shared\metrics\node_modules\typescript\bin\tsc
npx: installed 1 in 1.771s
The "path" argument must be of type string
machinelabs2\shared\supervisor\node_modules\typescript\bin\tsc
'.' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed: ./node_modules/typescript/bin/tsc
Done in 19.88s.
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '\machinelabs2\server\dist\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

#### Current behavior
See the stack trace above

#### How to reproduce
I can reproduce it everytime on my Windows machine just by running the command.

#### Please execute the following commands in your terminal and post the output here
Windows
node: v9.11.1

**Comment by Jefiozie** [comment]
@PascalPrecht I had a look at this issue and it looks it has something to do with this [build.js#23](https://github.com/machinelabs/machinelabs/blob/b29713fa9e22b7ffb1a66f43703e5f03c8dc3e70/server/build/build.js#L23) line. When changing this to `tsc` or `npx tsc` everything runs correctly.

I can make the change but I don't know if this change has a lot of impact?

**Comment by PascalPrecht** [comment]
I'm surprised this will fix it. Using just `tsc` will likely use the globally installed version (which we don't want to rely on), that's why we're using `./node_modules....` so we ensure we're always using the local version. `npx tsc` will do exactly the same so something must be off there.

**Comment by Jefiozie** [comment]
I believe the `npx tsc` will not be a problem. reading the docs it will install the required version based on the `package.json` when it is not found locally. So I don't see the harm of it.

> Executes <command> either from a local node_modules/.bin, or from a central cache, installing any packages needed in order for <command> to run.

> By default, npx will check whether <command> exists in $PATH, or in the local project binaries, and execute that. If <command> is not found, it will be installed prior to execution.

**Comment by PascalPrecht** [comment]
That's all correct. That's why I said 

> npx tsc will do exactly the same so something must be off there.

There's no harm with using npx, but unclarity over why `npx tsc` works and `./node_modules/tsc/bin` doesn't

**Comment by Jefiozie** [comment]
Okay thanks, made a PR for it 👍
